### ISSUE TITLE
support development with local disk file storage

### ISSUE THREAD

**Issue by elnygren** [pancentric/django-imgix#11]
I think it's a common setup to
a) use S3/GCS/whatever in prod/staging
b) use Django's local disk when developing on your own machine

Perhaps this library should support this workflow?
eg. if IMGIX_DOMAINS is not set, then don't do any processing?

possible workarounds:
- do `if DEBUG else` in template
- doing your own templatetag to wrap this one....

**Comment by luqven** [comment]
> Related to #8 

Hey there, thanks for reposting this issue. I know it's been, well more than a hot minute since you opened it, but we always welcome PRs.

Since there hasn't been any movement on this in some time, I'm going to go ahead and close this issue. But please comment should there still be interesting in tackling this and I'll be sure to re-open it.
